### ISSUE TITLE
Build your first topic has broken images

### ISSUE THREAD

**Issue by floreseken** [aspnet/Blazor.Docs#62] opened 2018-04-19 10:30 UTC
Here:

![image](https://user-images.githubusercontent.com/6927344/38986690-7533f048-43cd-11e8-997f-6162dc0472dc.png)

**Comment by guardrex** [comment] 2018-04-19 14:56
The problem here has turned out to be that the images aren't making their way to the live site deployment. I'll focus now on the docfx config and see why these aren't making their way over.

@floreseken In case you're wondering why/how simple links became a problem: This site is a one-off affair. The site has been built outside of our normal doc system, as Blazor is an experimental preview. Therefore, I've been *learning* how to put one together from scratch ... *learning the hard way*. 😅

**Comment by floreseken** [comment] 2018-04-19 14:57
I'll keep you sharp ;-)

**Comment by guardrex** [comment] 2018-04-19 15:00
Yes ... "sharp" ... and add to that "humbled" ... it's a bit humbling when after so many years in web dev I can't get a simple image to show up on a webpage! 🤦‍♂️ :smile: lol

I'll get it in a sec. I think I know what to change. *If these emails will stop hitting me every 15 seconds*, I should be able to get it done in a couple of minutes. 😅

**Comment by guardrex** [comment] 2018-04-19 16:07
ok ... that little hack-a-roo seems fine for now ...

http://blazor.net/docs/tutorials/build-your-first-blazor-app.html

@danroth27 If that's the way we should go (GH raw user content links), we can just keep doing that if you want. I'm curious about the cause of the problem. I've used GH Pages once before, but my setup is a bit different, so I can't make a direct comparison between sites.

**Comment by danroth27** [comment] 2018-04-19 16:53
I'm fine with this. I like the idea of keeping images out of the repo. Git isn't great for storing binary files. To keep things organized we might want to create specific issues in this repo with the images we add are storing on GitHub.

**Comment by guardrex** [comment] 2018-04-19 16:57
> keeping images out of the repo

Me, too. I :heart: Azure CDN for static bits.

>  create specific issues in this repo with the images we add are storing on GitHub.

I don't quite follow ...... I probably need a 2nd cup of :coffee: lol

**Comment by danroth27** [comment] 2018-04-19 17:05
Oh, sorry, I misunderstood what you did here. I thought you were doing something like this: http://blog.davidebbo.com/2014/11/using-issues-for-github-pages-screenshots.html :smile:

**Comment by guardrex** [comment] 2018-04-19 17:36
He makes good points, but I think his reasoning can be countered under our circumstances ...

* I don't think it's a major drop in productivity for us. We're only using images (usually) in tutorial topics. The vast majority of the content is reference material, and we seek to avoid images in reference material. The end result is that we hardly have enough images to sweat a major change to the workflow.
* History is a factor. It would be really painful with our workload to stop and go back and retool to a new strategy (for aspnet/Docs & dotnet/Docs). There would also be APEX issues/approvals to address (phone calls ... meetings ... emails ... testing ... omg ... it could take weeks/months ... *decades!* lol).
* Next, there's the problem of changing the links out when the doc set moves. Those links would be a real pain to change over (e.g., `https://cloud.githubusercontent.com/assets/556238/5241760/e17ae9f4-78d9-11e4-86f5-6e168adcea87.png`). For example, we're using `https://raw.githubusercontent.com/aspnet/Blazor.Docs/gh-pages/docs/tutorials/build-your-first-blazor-app/_static/new-aspnet-core-project.png`. These GH raw content links preserve path/file name ... very easy to mod that for the move to `build-your-first-blazor-app/_static/new-aspnet-core-project.png`.
* Even when we use them in reference topics, the images are right there. It's not a major loss in productivity imo to link them out of a folder sitting right next to the topic ... and yes, I think we do want the full history for the images we use.
* Finally, there's the issue of *MORE ISSUES* lying around 😨. Things are going to be very interesting when the reader feedback hits the main repos. Even *more* issues?? May the :pray: server gods :pray: save us! lol

The GH user content raw links pretty much do what he's is suggesting in terms of allowing the GH cloud to maintain them, while allowing us to easily conform on a move to aspnet/Docs. I think this will be stable and work well for now.

**Comment by danroth27** [comment] 2018-04-19 17:39
Sure :smiley:

**Comment by guardrex** [comment] 2018-04-19 17:45
Fixed by #65 

Thanks again @floreseken! :rocket:

**Closed by guardrex** 2018-04-19 17:45 UTC
